Repository itzenata/itzenata, pull requests merged in 2024-10, with the labels that each got.

#6 add whatsapp and new logo
  assets/images/LOGO_ITZENATA.png
  assets/images/itzenata-notxt-S.png
  blog-detail.html
  css/home.css
  css/style.css
  index.html
Labels: enhancement

#8 Feat/adding wattsup icon
  assets/images/blogs/antoine.jpg
  assets/images/blogs/injectedBlogsImages/creizmenn.jpeg
  data/blogsData.json
  index.html
Labels: enhancement

#9 fix the margin the description font size and change the logo to one w…
  assets/images/logo.png
  blog-detail.html
  css/home.css
  css/style.css
  index.html
Labels: bug, enhancement

#10 resolve design problem
  blog-detail.html
  css/style.css
  index.html
Labels: bug

#11 adding 100vh and 5% margin buttom for porjets section
  css/home.css
Labels: bug

#13 Feat/design responsabilite resloving
  css/home.css
  css/nav.css
  js/main.js
Labels: bug

#15 add some between the menu and his button
  css/nav.css
Labels: bug

#16 fix logo size also change the criezman blog with anither and put into…
  blog-detail.html
  css/blog-details.css
  css/nav.css
  data/blogsData.json
  index.html
Labels: bug

#17 Feat/adding berrad blog
  assets/images/blogs/berrada1.jpg
  assets/images/blogs/injectedBlogsImages/berrada2.jpg
  data/blogsData.json
Labels: enhancement
